import type { Config } from 'tailwindcss'

const beVietnam = ['"Be Vietnam Pro"', 'sans-serif'] as const

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        /* Brand scale (upgrade rules) */
        'primary-50': '#EFF6FF',
        'primary-400': '#60A5FA',
        'primary-500': '#3B82F6',
        'primary-600': '#2563EB',
        'primary-700': '#1D4ED8',
        'accent-400': '#FBBF24',
        'accent-500': '#F59E0B',
        'accent-600': '#D97706',
        'neutral-0': '#1E293B',
        'neutral-50': '#0F172A',
        'neutral-100': '#1E293B',
        'neutral-200': '#334155',
        'neutral-500': '#94A3B8',
        'neutral-700': '#CBD5E1',
        'neutral-900': '#F8FAFC',
        'success-500': '#22C55E',
        'danger-500': '#EF4444',
        'heritage-bronze': '#B45309',
        'heritage-crimson': '#B91C1C',
        'heritage-jade': '#0D9488',

        /* Semantic tokens — remapped to brand palette */
        primary: '#3B82F6',
        'on-primary': '#FFFFFF',
        'primary-container': '#2563EB',
        'primary-fixed': '#DBEAFE',
        'primary-fixed-dim': '#60A5FA',
        'on-primary-fixed': '#1E3A8A',
        'on-primary-fixed-variant': '#1D4ED8',
        'on-primary-container': '#EFF6FF',
        'surface-tint': '#3B82F6',
        'inverse-primary': '#60A5FA',

        secondary: '#5EEAD4',
        'on-secondary': '#0F172A',
        'secondary-container': '#0D9488',
        'on-secondary-container': '#CCFBF1',
        'secondary-fixed': '#5EEAD4',
        'secondary-fixed-dim': '#2DD4BF',
        'on-secondary-fixed': '#0F172A',
        'on-secondary-fixed-variant': '#115E59',

        accent: '#F59E0B',
        tertiary: '#ffb4aa',
        'tertiary-container': '#ff8a7b',
        'on-tertiary': '#690003',
        'on-tertiary-container': '#840507',
        'on-tertiary-fixed': '#410001',
        'on-tertiary-fixed-variant': '#8f100d',
        'tertiary-fixed-dim': '#ffb4aa',
        'tertiary-fixed': '#ffdad5',

        background: '#0F172A',
        surface: '#0F172A',
        'surface-dim': '#0F172A',
        'surface-bright': '#1E293B',
        'surface-container-lowest': '#0F172A',
        'surface-container-low': '#1E293B',
        'surface-container': '#1E293B',
        'surface-container-high': '#334155',
        'surface-container-highest': '#334155',
        'surface-variant': '#334155',
        'on-background': '#F1F5F9',
        'on-surface': '#F1F5F9',
        'on-surface-variant': '#94A3B8',
        'inverse-surface': '#F1F5F9',
        'inverse-on-surface': '#0F172A',

        outline: '#64748B',
        'outline-variant': '#334155',
        error: '#EF4444',
        'on-error': '#FFFFFF',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1rem',
        full: '9999px',
      },
      boxShadow: {
        'elev-1': '0 4px 12px rgba(0, 0, 0, 0.25), 0 1px 3px rgba(0, 0, 0, 0.15)',
        'elev-2': '0 8px 24px rgba(0, 0, 0, 0.35), 0 2px 6px rgba(0, 0, 0, 0.2)',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'safe-area-inset': '20px',
      },
      maxWidth: {
        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
      },
      fontFamily: {
        sans: [...beVietnam],
        'body-md': [...beVietnam],
        'title-md': [...beVietnam],
        'headline-lg-mobile': [...beVietnam],
        'headline-lg': [...beVietnam],
        'label-sm': [...beVietnam],
        'display-lg': [...beVietnam],
        'body-lg': [...beVietnam],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg-mobile': [
          '22px',
          { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'headline-lg': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'label-sm': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'display-lg': [
          '34px',
          { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
} satisfies Config
