import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#33343d',
        'on-primary-fixed': '#261900',
        'primary-container': '#e6a832',
        'surface-bright': '#383941',
        'on-error': '#690005',
        'tertiary-container': '#ff8a7b',
        'secondary-fixed-dim': '#5EEAD4',
        'inverse-surface': '#e3e1ed',
        'on-tertiary-fixed': '#410001',
        tertiary: '#ffb4aa',
        'surface-tint': '#FFB547',
        'primary-fixed-dim': '#FFB547',
        'on-surface': '#e3e1ed',
        'error-container': '#93000a',
        'surface-container-highest': '#33343d',
        'inverse-on-surface': '#2f3038',
        'surface-dim': '#14151f',
        primary: '#FFB547',
        'on-secondary': '#003735',
        'surface-container-lowest': '#0d0e15',
        'on-primary': '#402d00',
        'surface-container-high': '#292932',
        'on-primary-fixed-variant': '#5c4300',
        'surface-container': '#1c1d28',
        'on-tertiary-fixed-variant': '#8f100d',
        'on-background': '#e3e1ed',
        'secondary-container': '#00bcb6',
        'on-tertiary': '#690003',
        secondary: '#5EEAD4',
        accent: '#A78BFA',
        'on-tertiary-container': '#840507',
        'surface-container-low': '#1a1b23',
        'secondary-fixed': '#68f8f1',
        outline: '#64748b',
        'on-secondary-fixed-variant': '#00504d',
        'primary-fixed': '#ffdea1',
        surface: '#14151f',
        'on-secondary-container': '#004543',
        'on-error-container': '#ffdad6',
        'on-primary-container': '#533c00',
        'outline-variant': '#334155',
        'tertiary-fixed-dim': '#ffb4aa',
        'tertiary-fixed': '#ffdad5',
        'on-surface-variant': '#94a3b8',
        'inverse-primary': '#7a5900',
        'on-secondary-fixed': '#00201f',
        error: '#ffb4ab',
        background: '#14151f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1rem',
        full: '9999px',
      },
      boxShadow: {
        'elev-1': '0 4px 12px rgba(0, 0, 0, 0.25), 0 1px 3px rgba(0, 0, 0, 0.15)',
        'elev-2': '0 8px 24px rgba(0, 0, 0, 0.35), 0 2px 6px rgba(0, 0, 0, 0.2)',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'safe-area-inset': '20px',
      },
      maxWidth: {
        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
      },
      fontFamily: {
        'body-md': ['"Montserrat"', 'sans-serif'],
        'title-md': ['"Montserrat"', 'sans-serif'],
        'headline-lg-mobile': ['"Outfit"', '"Montserrat"', 'sans-serif'],
        'headline-lg': ['"Outfit"', '"Montserrat"', 'sans-serif'],
        'label-sm': ['"Montserrat"', 'sans-serif'],
        'display-lg': ['"Outfit"', '"Montserrat"', 'sans-serif'],
        'body-lg': ['"Montserrat"', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg-mobile': [
          '22px',
          { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'headline-lg': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'label-sm': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' },
        ],
        'display-lg': [
          '34px',
          { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
} satisfies Config
